image: node:10.15.0

before_script:
  - npm install

cache:
  paths:
    - node_modules/

all_tests:
  script:
    - npm run build

test:lint:
  script:
    - npm run lint

test:main:
  script:
    - npm test

publish:  
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - npm run build
    - export NPM_TOKEN=$NPM_TOKEN
    - npm publish
