image: node:12.0

before_script:
  - npm i

cache:
  paths:
    - node_modules/

test:
  script:
    - npm test

lint:
  script:
    - npm run lint

publish:  
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - npm run build
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish
