name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup
      uses: actions/setup-node@v1
      with:
        version: 12.x
    - name: Verify
      run: |
        npm ci
        npm run preversion
    - name: Publish
      run: |
        npm adduser --registry=https://registry.npmjs.com
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
